import CryptoFraudDetection.scraper.comparitech
import CryptoFraudDetection.scraper.discord
import CryptoFraudDetection.scraper.google_results
import CryptoFraudDetection.scraper.google_trends
import CryptoFraudDetection.scraper.reddit
import CryptoFraudDetection.scraper.telegram
import CryptoFraudDetection.scraper.x

import CryptoFraudDetection.scraper.utils
